# Generated by Django 4.2.5 on 2023-09-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
