# Generated by Django 4.2.5 on 2023-09-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_amount_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_added',
            field=models.DateField(auto_now_add=True, default='2023-01-01'),
            preserve_default=False,
        ),
    ]
