# Generated by Django 4.2.5 on 2023-09-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_item_data_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True, default='2023-01-01'),
            preserve_default=False,
        ),
    ]
