# Generated by Django 4.2.5 on 2023-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_discout',
            field=models.BooleanField(default='False'),
        ),
    ]
