# Generated by Django 4.2.5 on 2023-11-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_is_discout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_discout',
            new_name='is_discount',
        ),
    ]
